services:
  gpustack-server:
    image: ${IMAGE_REGISTRY:-registry.cn-chengdu.aliyuncs.com}/${IMAGE_NAMESPACE:-lmzjai}/gpustack-custom:${GPUSTACK_TAG:-dev}
    container_name: gpustack-server
    restart: unless-stopped
    volumes:
      - gpustack-data:/var/lib/gpustack
    ports:
      - "8080:80"

volumes:
  gpustack-data: {}
