services:
  gpustack-server:
    image: ${IMAGE_REGISTRY:-registry.cn-chengdu.aliyuncs.com}/${IMAGE_NAMESPACE:-lmzjai}/gpustack-custom:${GPUSTACK_TAG:-dev}
    container_name: gpustack-server
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - gpustack-data:/var/lib/gpustack
    ports:
      - "8080:80"
    networks:
      - docker_default

volumes:
  gpustack-data: {}

networks:
  docker_default:
    external: true
